### ISSUE TITLE
Ending parenthesis in complex expression removed

### ISSUE THREAD

**Issue by jmolero** [hrsh7th/cmp-calc#5]
Thanks for the recent addition that allows more complex expressions.

I found a small issue with it. if the expression ends in a closing parenthesis, it is removed when the equal sign and the result is added.

**Comment by kdurant** [comment]
I encount this issue too.

**Comment by litoj** [comment]
I think the latest update should have fixed this (#6)

**Comment by jmolero** [comment]
I just tried and cannot reproduce the issue anymore. Thanks a lot!
